### ISSUE TITLE
Tracebacks not printing during remote execution

### ISSUE THREAD

**Issue by avirshup** [Autodesk/molecular-design-toolkit#16]
```
Traceback (most recent call last):
  File "run_job.py", line 86, in <module>
    cp.dump(exc, excfile)
  File "/usr/lib/python2.7/copy_reg.py", line 70, in _reduce_ex
    raise TypeError, "can't pickle %s objects" % base.__name__
TypeError: can't pickle StringO objects
```

**Comment by avirshup** [comment]
This was fixed at some point :)
