### ISSUE TITLE
Error installing with pip

### ISSUE THREAD

**Issue by pnave95** [Autodesk/molecular-design-toolkit#189]
## Bug report
I am trying to install moldesign through pip, but I receive an error stating that nbmolviz 0.7.0 has requirement moldesign>=0.8rc1, which I believe is the development version?  If so, it seems that maybe nbmolviz is prematurely assuming the next version of moldesign and in the process is breaking the version currently available through pip.  Any help getting past this issue so that I can successfully set up moldesign 0.7.3 would be greatly appreciated.  Thanks!  (errors from pip included below)
#### Steps to reproduce

pip2 install --user moldesign

Here is the portion of the output containing the error:

nbmolviz 0.7.0 has requirement moldesign>=0.8rc1, but you'll have moldesign 0.7.3 which is incompatible.

#### Environment
  - Operating system: Ubuntu 16.04 
  - `python --version` output: 2.7.12
  - `pip show moldesign nbmolviz | grep -B1 Version` output:
Name: moldesign
Version: 0.7.3
--
Name: nbmolviz
Version: 0.7.0

**Comment by diegovalenzuelaiturra** [comment]
Collecting moldesign
  Using cached https://files.pythonhosted.org/packages/62/c7/be710ec938ceb066f06ccbfd9e2f67860f47edb493efbae52ba3cb40c2bb/moldesign-0.7.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-pymnxii1/moldesign/setup.py", line 70
        print 'Thank you for installing the Molecular Design Toolkit!!!'
                                                                       ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Thank you for installing the Molecular Design Toolkit!!!')?
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-pymnxii1/moldesign/

**Comment by pnave95** [comment]
@diegovalenzuelaiturra I'm sorry, but I don't follow what you are saying.  Are you telling me something to try?  Can you please be a little more clear?

**Comment by fcanomar** [comment]
Installing nbmolviz with pip after receiving this message doing
$ pip install nbmolviz
worked for me.
