### ISSUE TITLE
Install failure?

### ISSUE THREAD

**Issue by joseph-schaeffer** [Autodesk/molecular-design-toolkit#31]
Crashed at the end of `pip install moldesign`:

```
$ pip install -U moldesign && python -m moldesign intro
Collecting moldesign
  Downloading moldesign-0.7.2.tar.gz (19.1MB)
    100% |████████████████████████████████| 19.1MB 66kB/s 
Collecting biopython (from moldesign)
  Downloading biopython-1.67.tar.gz (14.3MB)
    100% |████████████████████████████████| 14.3MB 86kB/s 
Collecting docker-py (from moldesign)
  Downloading docker_py-1.9.0-py2.py3-none-any.whl (42kB)
    100% |████████████████████████████████| 51kB 7.4MB/s 
Collecting fortranformat (from moldesign)
  Downloading fortranformat-0.2.5.tar.gz
Collecting funcsigs (from moldesign)
  Downloading funcsigs-1.0.2-py2.py3-none-any.whl
Collecting ipywidgets>=5.1 (from moldesign)
  Downloading ipywidgets-5.2.2-py2.py3-none-any.whl (43kB)
    100% |████████████████████████████████| 51kB 10.8MB/s 
Collecting ipython>=4.2 (from moldesign)
  Downloading ipython-5.0.0-py2.py3-none-any.whl (743kB)
    100% |████████████████████████████████| 747kB 1.5MB/s 
Collecting markdown2 (from moldesign)
  Downloading markdown2-2.3.1.zip (147kB)
    100% |████████████████████████████████| 153kB 5.9MB/s 
Collecting matplotlib (from moldesign)
  Downloading matplotlib-1.5.1-cp27-none-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (49.7MB)
    100% |████████████████████████████████| 49.7MB 25kB/s 
Collecting nbmolviz>=0.6.5 (from moldesign)
  Downloading nbmolviz-0.6.6.tar.gz (572kB)
    100% |████████████████████████████████| 573kB 2.1MB/s 
Collecting notebook>=4.2 (from moldesign)
  Downloading notebook-4.2.1-py2.py3-none-any.whl (6.7MB)
    100% |████████████████████████████████| 6.7MB 190kB/s 
Collecting numpy (from moldesign)
  Downloading numpy-1.11.1-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (3.9MB)
    100% |████████████████████████████████| 3.9MB 329kB/s 
Collecting pint>=0.7 (from moldesign)
  Downloading Pint-0.7.2.tar.gz (149kB)
    100% |████████████████████████████████| 153kB 6.1MB/s 
Collecting pyccc>=0.6.4 (from moldesign)
  Downloading pyccc-0.6.5.tar.gz (45kB)
    100% |████████████████████████████████| 51kB 9.1MB/s 
Collecting pytest (from moldesign)
  Downloading pytest-2.9.2-py2.py3-none-any.whl (162kB)
    100% |████████████████████████████████| 163kB 6.8MB/s 
Collecting pyyaml (from moldesign)
  Downloading PyYAML-3.11.zip (371kB)
    100% |████████████████████████████████| 378kB 3.0MB/s 
Collecting requests (from moldesign)
  Downloading requests-2.10.0-py2.py3-none-any.whl (506kB)
    100% |████████████████████████████████| 512kB 2.3MB/s 
Collecting scipy (from moldesign)
  Downloading scipy-0.18.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (21.9MB)
    100% |████████████████████████████████| 21.9MB 58kB/s 
Collecting webcolors (from moldesign)
  Downloading webcolors-1.5.tar.gz
Collecting ipaddress>=1.0.16; python_version < "3.3" (from docker-py->moldesign)
  Downloading ipaddress-1.0.16-py27-none-any.whl
Collecting websocket-client>=0.32.0 (from docker-py->moldesign)
  Downloading websocket_client-0.37.0.tar.gz (194kB)
    100% |████████████████████████████████| 194kB 5.8MB/s 
Requirement already up-to-date: six>=1.4.0 in /usr/local/lib/python2.7/site-packages (from docker-py->moldesign)
Collecting backports.ssl-match-hostname>=3.5; python_version < "3.5" (from docker-py->moldesign)
  Downloading backports.ssl_match_hostname-3.5.0.1.tar.gz
Collecting ipykernel>=4.2.2 (from ipywidgets>=5.1->moldesign)
  Downloading ipykernel-4.3.1-py2.py3-none-any.whl (93kB)
    100% |████████████████████████████████| 102kB 9.6MB/s 
Collecting widgetsnbextension>=1.2.6 (from ipywidgets>=5.1->moldesign)
  Downloading widgetsnbextension-1.2.6-py2.py3-none-any.whl (1.5MB)
    100% |████████████████████████████████| 1.5MB 911kB/s 
Collecting traitlets>=4.2.1 (from ipywidgets>=5.1->moldesign)
  Downloading traitlets-4.2.2-py2.py3-none-any.whl (68kB)
    100% |████████████████████████████████| 71kB 7.7MB/s 
Collecting pygments (from ipython>=4.2->moldesign)
  Downloading Pygments-2.1.3-py2.py3-none-any.whl (755kB)
    100% |████████████████████████████████| 757kB 1.6MB/s 
Collecting setuptools>=18.5 (from ipython>=4.2->moldesign)
  Downloading setuptools-25.1.1-py2.py3-none-any.whl (442kB)
    100% |████████████████████████████████| 450kB 2.5MB/s 
Collecting backports.shutil-get-terminal-size; python_version == "2.7" (from ipython>=4.2->moldesign)
  Downloading backports.shutil_get_terminal_size-1.0.0-py2.py3-none-any.whl
Collecting pickleshare (from ipython>=4.2->moldesign)
  Downloading pickleshare-0.7.3-py2.py3-none-any.whl
Collecting decorator (from ipython>=4.2->moldesign)
  Downloading decorator-4.0.10-py2.py3-none-any.whl
Collecting simplegeneric>0.8 (from ipython>=4.2->moldesign)
  Downloading simplegeneric-0.8.1.zip
Collecting pexpect; sys_platform != "win32" (from ipython>=4.2->moldesign)
  Downloading pexpect-4.2.0-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 61kB 9.3MB/s 
Collecting pathlib2; python_version == "2.7" or python_version == "3.3" (from ipython>=4.2->moldesign)
  Downloading pathlib2-2.1.0-py2.py3-none-any.whl
Collecting prompt-toolkit<2.0.0,>=1.0.3 (from ipython>=4.2->moldesign)
  Downloading prompt_toolkit-1.0.3-py2-none-any.whl (249kB)
    100% |████████████████████████████████| 256kB 4.5MB/s 
Collecting appnope; sys_platform == "darwin" (from ipython>=4.2->moldesign)
  Downloading appnope-0.1.0-py2.py3-none-any.whl
Collecting pytz (from matplotlib->moldesign)
  Downloading pytz-2016.6.1-py2.py3-none-any.whl (481kB)
    100% |████████████████████████████████| 481kB 2.6MB/s 
Collecting cycler (from matplotlib->moldesign)
  Downloading cycler-0.10.0-py2.py3-none-any.whl
Collecting pyparsing!=2.0.0,!=2.0.4,>=1.5.6 (from matplotlib->moldesign)
  Downloading pyparsing-2.1.5-py2.py3-none-any.whl (42kB)
    100% |████████████████████████████████| 51kB 7.5MB/s 
Collecting python-dateutil (from matplotlib->moldesign)
  Downloading python_dateutil-2.5.3-py2.py3-none-any.whl (201kB)
    100% |████████████████████████████████| 204kB 5.5MB/s 
Collecting uuid (from nbmolviz>=0.6.5->moldesign)
  Downloading uuid-1.30.tar.gz
Requirement already up-to-date: jinja2 in /usr/local/lib/python2.7/site-packages (from notebook>=4.2->moldesign)
Collecting terminado>=0.3.3; sys_platform != "win32" (from notebook>=4.2->moldesign)
  Downloading terminado-0.6.tar.gz
Collecting tornado>=4 (from notebook>=4.2->moldesign)
  Downloading tornado-4.4.1.tar.gz (456kB)
    100% |████████████████████████████████| 460kB 2.5MB/s 
Collecting nbconvert (from notebook>=4.2->moldesign)
  Downloading nbconvert-4.2.0-py2.py3-none-any.whl (319kB)
    100% |████████████████████████████████| 327kB 3.6MB/s 
Collecting jupyter-client (from notebook>=4.2->moldesign)
  Downloading jupyter_client-4.3.0-py2.py3-none-any.whl (76kB)
    100% |████████████████████████████████| 81kB 7.5MB/s 
Collecting nbformat (from notebook>=4.2->moldesign)
  Downloading nbformat-4.0.1-py2.py3-none-any.whl (138kB)
    100% |████████████████████████████████| 143kB 8.0MB/s 
Collecting ipython-genutils (from notebook>=4.2->moldesign)
  Downloading ipython_genutils-0.1.0-py2.py3-none-any.whl
Collecting jupyter-core (from notebook>=4.2->moldesign)
  Downloading jupyter_core-4.1.0-py2.py3-none-any.whl (76kB)
    100% |████████████████████████████████| 81kB 10.2MB/s 
Collecting tblib (from pyccc>=0.6.4->moldesign)
  Downloading tblib-1.3.0-py2.py3-none-any.whl
Collecting py>=1.4.29 (from pytest->moldesign)
  Downloading py-1.4.31-py2.py3-none-any.whl (81kB)
    100% |████████████████████████████████| 92kB 9.9MB/s 
Collecting ptyprocess>=0.5 (from pexpect; sys_platform != "win32"->ipython>=4.2->moldesign)
  Downloading ptyprocess-0.5.1-py2.py3-none-any.whl
Collecting wcwidth (from prompt-toolkit<2.0.0,>=1.0.3->ipython>=4.2->moldesign)
  Downloading wcwidth-0.1.7-py2.py3-none-any.whl
Requirement already up-to-date: MarkupSafe in /usr/local/lib/python2.7/site-packages (from jinja2->notebook>=4.2->moldesign)
Collecting singledispatch (from tornado>=4->notebook>=4.2->moldesign)
  Downloading singledispatch-3.4.0.3-py2.py3-none-any.whl
Collecting certifi (from tornado>=4->notebook>=4.2->moldesign)
  Downloading certifi-2016.2.28-py2.py3-none-any.whl (366kB)
    100% |████████████████████████████████| 368kB 3.3MB/s 
Collecting backports_abc>=0.4 (from tornado>=4->notebook>=4.2->moldesign)
  Downloading backports_abc-0.4-py2.py3-none-any.whl
Collecting entrypoints (from nbconvert->notebook>=4.2->moldesign)
  Downloading entrypoints-0.2.2-py2.py3-none-any.whl
Collecting mistune!=0.6 (from nbconvert->notebook>=4.2->moldesign)
  Downloading mistune-0.7.3-py2.py3-none-any.whl
Collecting pyzmq>=13 (from jupyter-client->notebook>=4.2->moldesign)
  Downloading pyzmq-15.3.0-cp27-cp27m-macosx_10_6_intel.whl (1.0MB)
    100% |████████████████████████████████| 1.0MB 1.3MB/s 
Collecting jsonschema!=2.5.0,>=2.0 (from nbformat->notebook>=4.2->moldesign)
  Downloading jsonschema-2.5.1-py2.py3-none-any.whl
Collecting configparser>=3.5; python_version == "2.7" (from entrypoints->nbconvert->notebook>=4.2->moldesign)
  Downloading configparser-3.5.0.tar.gz
Collecting functools32; python_version == "2.7" (from jsonschema!=2.5.0,>=2.0->nbformat->notebook>=4.2->moldesign)
  Downloading functools32-3.2.3-2.zip
Installing collected packages: biopython, ipaddress, websocket-client, requests, backports.ssl-match-hostname, docker-py, fortranformat, funcsigs, ipython-genutils, decorator, traitlets, pygments, setuptools, backports.shutil-get-terminal-size, pathlib2, pickleshare, simplegeneric, ptyprocess, pexpect, wcwidth, prompt-toolkit, appnope, ipython, pyzmq, jupyter-core, jupyter-client, singledispatch, certifi, backports-abc, tornado, ipykernel, terminado, functools32, jsonschema, nbformat, configparser, entrypoints, mistune, nbconvert, notebook, widgetsnbextension, ipywidgets, markdown2, pytz, cycler, pyparsing, python-dateutil, numpy, matplotlib, uuid, webcolors, nbmolviz, pint, tblib, pyccc, py, pytest, pyyaml, scipy, moldesign
  Found existing installation: biopython 1.62
    Uninstalling biopython-1.62:
      Successfully uninstalled biopython-1.62
  Running setup.py install for biopython ... done
  Running setup.py install for websocket-client ... done
  Found existing installation: requests 2.3.0
    Uninstalling requests-2.3.0:
      Successfully uninstalled requests-2.3.0
  Found existing installation: backports.ssl-match-hostname 3.4.0.2
    Uninstalling backports.ssl-match-hostname-3.4.0.2:
      Successfully uninstalled backports.ssl-match-hostname-3.4.0.2
  Running setup.py install for backports.ssl-match-hostname ... done
  Running setup.py install for fortranformat ... done
  Found existing installation: Pygments 2.1.1
    Uninstalling Pygments-2.1.1:
      Successfully uninstalled Pygments-2.1.1
  Found existing installation: setuptools 12.0.5
    Uninstalling setuptools-12.0.5:
      Successfully uninstalled setuptools-12.0.5
  Running setup.py install for simplegeneric ... done
  Found existing installation: ptyprocess 0.4
    Uninstalling ptyprocess-0.4:
      Successfully uninstalled ptyprocess-0.4
  Found existing installation: ipython 3.1.0
    Uninstalling ipython-3.1.0:
      Successfully uninstalled ipython-3.1.0
  Found existing installation: pyzmq 14.6.0
    Uninstalling pyzmq-14.6.0:
      Successfully uninstalled pyzmq-14.6.0
  Found existing installation: certifi 2015.4.28
    Uninstalling certifi-2015.4.28:
      Successfully uninstalled certifi-2015.4.28
  Found existing installation: tornado 4.1
    Uninstalling tornado-4.1:
      Successfully uninstalled tornado-4.1
  Running setup.py install for tornado ... done
  Found existing installation: terminado 0.5
    Uninstalling terminado-0.5:
      Successfully uninstalled terminado-0.5
  Running setup.py install for terminado ... done
  Running setup.py install for functools32 ... done
  Found existing installation: jsonschema 2.4.0
    Uninstalling jsonschema-2.4.0:
      Successfully uninstalled jsonschema-2.4.0
  Running setup.py install for configparser ... done
  Found existing installation: mistune 0.5.1
    Uninstalling mistune-0.5.1:
      Successfully uninstalled mistune-0.5.1
  Running setup.py install for markdown2 ... done
  Found existing installation: pytz 2015.7
    Uninstalling pytz-2015.7:
      Successfully uninstalled pytz-2015.7
  Found existing installation: pyparsing 2.0.3
    Uninstalling pyparsing-2.0.3:
      Successfully uninstalled pyparsing-2.0.3
  Found existing installation: python-dateutil 2.4.2
    Uninstalling python-dateutil-2.4.2:
      Successfully uninstalled python-dateutil-2.4.2
  Found existing installation: numpy 1.9.2
    Uninstalling numpy-1.9.2:
      Successfully uninstalled numpy-1.9.2
  Found existing installation: matplotlib 1.4.3
    Uninstalling matplotlib-1.4.3:
      Successfully uninstalled matplotlib-1.4.3
  Running setup.py install for uuid ... done
  Running setup.py install for webcolors ... done
  Running setup.py install for nbmolviz ... done
  Running setup.py install for pint ... done
  Running setup.py install for pyccc ... done
  Running setup.py install for pyyaml ... done
  Running setup.py install for moldesign ... done
Successfully installed appnope backports-abc backports.shutil-get-terminal-size backports.ssl-match-hostname biopython certifi configparser cycler decorator docker-py entrypoints fortranformat funcsigs functools32 ipaddress ipykernel ipython ipython-genutils ipywidgets jsonschema jupyter-client jupyter-core markdown2 matplotlib mistune moldesign nbconvert nbformat nbmolviz notebook numpy pathlib2 pexpect pickleshare pint prompt-toolkit ptyprocess py pyccc pygments pyparsing pytest python-dateutil pytz pyyaml pyzmq requests scipy setuptools simplegeneric singledispatch tblib terminado tornado traitlets uuid wcwidth webcolors websocket-client widgetsnbextension
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/pip/__init__.py", line 221, in main
    return command.main(cmd_args)
  File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 252, in main
    pip_version_check(session)
  File "/usr/local/lib/python2.7/site-packages/pip/utils/outdated.py", line 102, in pip_version_check
    installed_version = get_installed_version("pip")
  File "/usr/local/lib/python2.7/site-packages/pip/utils/__init__.py", line 848, in get_installed_version
    working_set = pkg_resources.WorkingSet()
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 619, in __init__
    self.add_entry(entry)
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 675, in add_entry
    for dist in find_distributions(entry, True):
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1942, in find_eggs_in_zip
    if metadata.has_metadata('PKG-INFO'):
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1463, in has_metadata
    return self.egg_info and self._has(self._fn(self.egg_info, name))
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1824, in _has
    return zip_path in self.zipinfo or zip_path in self._index()
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1704, in zipinfo
    return self._zip_manifests.load(self.loader.archive)
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1644, in load
    mtime = os.stat(path).st_mtime
OSError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/site-packages/setuptools-12.0.5-py2.7.egg'
```

It appears that moldesign has possibly installed successfully even with this error: 

```
$ python -c "import moldesign; moldesign.data.print_environment()"
No config file found at /Users/joseph/.moldesign/moldesign.yml - using defaults
{"env": {"platform": "darwin", "version": "2.7.9 (default, Mar  2 2015, 16:50:16) \n[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.54)]"}, "versions": {"Bio": "1.67", "jupyter": "???", "jupyter_client": "4.3.0", "pyccc": "0.6.5", "jupyter_core": "4.1.0", "openbabel": "FAILED", "matplotlib": "1.5.1", "moldesign": "0.7.2", "pyscf": "FAILED", "simtk": "???", "IPython": "5.0.0", "docker": "1.9.0", "pint": "0.7.2", "numpy": "1.11.1", "ipywidgets": "5.2.2", "nbmolviz": "0.6.6"}}
```

Setuptools appears to already be installed:
```
$ pip list | grep setup
setuptools (25.1.1)
```

Python 2.7.9 is my current installed version, via Homebrew (http://brew.sh).

**Comment by joseph-schaeffer** [comment]
Following up with more info as requested by @avirshup:

```
$ pip --version
pip 8.1.2 from /usr/local/lib/python2.7/site-packages (python 2.7)
```

Running the notebook (`python -m moldesign intro`) had no issues and I was able to do all steps from Example 1 without any problems.

**Comment by avirshup** [comment]
Thanks for the report, Joseph!

For posterity: This appears to be pypa/pip#2545. The problem, as best as I can understand, is that setuptools was NOT installed with `pip` (it probably came with homebrew instead). However, `pip -U moldesign` upgraded it anyway (here, from v 12.X -> v 25.X) - this is the expected behavior.

The problem is that, when trying to clean up outdated metadata, `pip` tries to remove the old `.egg-info` file, which was never created. So `pip` crashes, leaving some extra metadata lying around, which _probably_ doesn't affect anything. (?)

@joseph-schaeffer, could you try running `pip install -U moldesign` again to see if the message reappears? Hopefully, this is a one-time cosmetic error for when you update `setuptools`.

**Comment by joseph-schaeffer** [comment]
@avirshup: Ran it again with no message reappearing. I agree, looks like the referenced issue with pip rather than anything directly with mdt.
