### ISSUE TITLE
Installation fails with default mac python distro - need to install with sudo

### ISSUE THREAD

**Issue by florencio-mazzoldi** [Autodesk/molecular-design-toolkit#32]
End of the installation output:

```
Collecting jsonschema!=2.5.0,>=2.0 (from nbformat->notebook>=4.2->moldesign)
  Downloading jsonschema-2.5.1-py2.py3-none-any.whl
Collecting mistune!=0.6 (from nbconvert->notebook>=4.2->moldesign)
  Downloading mistune-0.7.3-py2.py3-none-any.whl
Collecting entrypoints (from nbconvert->notebook>=4.2->moldesign)
  Downloading entrypoints-0.2.2-py2.py3-none-any.whl
Requirement already up-to-date: MarkupSafe in /Library/Python/2.7/site-packages (from jinja2->notebook>=4.2->moldesign)
Collecting functools32 (from jsonschema!=2.5.0,>=2.0->nbformat->notebook>=4.2->moldesign)
  Downloading functools32-3.2.3-2.zip
Collecting configparser>=3.5 (from entrypoints->nbconvert->notebook>=4.2->moldesign)
  Downloading configparser-3.5.0.tar.gz
Installing collected packages: biopython, backports.ssl-match-hostname, ipaddress, requests, websocket-client, docker-py, fortranformat, funcsigs, pygments, pathlib2, pickleshare, simplegeneric, appnope, backports.shutil-get-terminal-size, decorator, ipython-genutils, traitlets, setuptools, ptyprocess, pexpect, wcwidth, prompt-toolkit, ipython, singledispatch, certifi, backports-abc, tornado, jupyter-core, pyzmq, jupyter-client, ipykernel, functools32, jsonschema, nbformat, mistune, jinja2, configparser, entrypoints, nbconvert, terminado, notebook, widgetsnbextension, ipywidgets, markdown2, numpy, pytz, python-dateutil, cycler, pyparsing, matplotlib, uuid, webcolors, nbmolviz, pint, tblib, pyccc, py, pytest, pyyaml, scipy, moldesign
  Found existing installation: biopython 1.63
    Uninstalling biopython-1.63:
Exception:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip/basecommand.py", line 211, in main
    status = self.run(options, args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip/commands/install.py", line 311, in run
    root=options.root_path,
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip/req/req_set.py", line 640, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip/req/req_install.py", line 716, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip/req/req_uninstall.py", line 125, in remove
    renames(path, new_path)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip/utils/__init__.py", line 315, in renames
    shutil.move(old, new)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 300, in move
    rmtree(src)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 250, in rmtree
    os.remove(fullname)
OSError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/biopython-1.63-py2.7-macosx-10.9-intel.egg/Bio/__init__.py'
You are using pip version 7.1.2, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

This is using the default mac osx python 2.7. It looks like everything in /Library/Python/2.7/site-packages is owned by root.

**Comment by florencio-mazzoldi** [comment]
```
python --version
Python 2.7.11
```

**Comment by florencio-mazzoldi** [comment]
```
which python
/Library/Frameworks/Python.framework/Versions/2.7/bin/python
```

**Comment by florencio-mazzoldi** [comment]
```
pip --version
pip 7.1.2 from /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (python 2.7)
```

**Comment by florencio-mazzoldi** [comment]
I just upgraded pip to 8.1.2

**Comment by avirshup** [comment]
Actually, this might be expected for the default mac system installation - everything needs to be installed with `sudo`. @florencio-mazzoldi, could you try `sudo pip install -U moldesign`?

**Comment by florencio-mazzoldi** [comment]
It all worked with sudo.

```
python -c "import moldesign; moldesign.data.print_environment()"
No config file found at /Users/flo/.moldesign/moldesign.yml - using defaults
{"env": {"platform": "darwin", "version": "2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 12:54:16) \n[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]"}, "versions": {"Bio": "1.67", "jupyter": "???", "jupyter_client": "4.3.0", "pyccc": "0.6.5", "jupyter_core": "4.1.0", "openbabel": "FAILED", "matplotlib": "1.5.1", "moldesign": "0.7.2", "pyscf": "FAILED", "simtk": "FAILED", "IPython": "5.0.0", "docker": "1.9.0", "pint": "0.7.2", "numpy": "1.11.1", "ipywidgets": "5.2.2", "nbmolviz": "0.6.6"}}
```

**Comment by avirshup** [comment]
Reopening this, because the documentation needs to reflect that this pretty common situation! We certainly need to update the API docs, but should probably update the web page and readme as well.

**Comment by avirshup** [comment]
These appear to be general python/pip problems, not specific to MDT. Solution is to start pushing users towards conda packages.

**Comment by hainm** [comment]
```bash
pip install --user
``` 
should work
