### ISSUE TITLE
`sudo pip install moldesign` fails with `OperationNotPermitted` on OS X

### ISSUE THREAD

**Issue by avirshup** [Autodesk/molecular-design-toolkit#43]
This appears to be pypa/pip#3165

We'll need to get our hands on a machine to test, but the workaround is likely:

~~pip install -U moldesign --ignore-installed six~~

`sudo pip install --no-deps -U moldesign pyccc nbmolviz`

To fix, we'll need to reproduce bug, confirm workaround, and update documentation

**Comment by dgasmith** [comment]
This does appear to avoid the `six` error; however, even with `sudo` I still hit the following:

```
Collecting configparser>=3.5; python_version == "2.7" (from entrypoints->nbconvert->notebook>=4.2->moldesign)
Collecting functools32; python_version == "2.7" (from jsonschema!=2.5.0,>=2.0->nbformat->notebook>=4.2->moldesign)
Installing collected packages: webcolors, requests, funcsigs, tblib, pyccc, simplegeneric, ptyprocess, pexpect, backports.shutil-get-terminal-size, six, wcwidth, prompt-toolkit, decorator, ipython-genutils, traitlets, pygments, setuptools, pathlib2, pickleshare, appnope, ipython, cycler, pytz, numpy, python-dateutil, pyparsing, matplotlib, biopython, fortranformat, MarkupSafe, jinja2, singledispatch, certifi, backports-abc, tornado, pyzmq, jupyter-core, jupyter-client, ipykernel, mistune, configparser, entrypoints, functools32, jsonschema, nbformat, nbconvert, terminado, notebook, pyyaml, websocket-client, ipaddress, backports.ssl-match-hostname, docker-py, py, pytest, scipy, uuid, widgetsnbextension, ipywidgets, nbmolviz, markdown2, pint, moldesign
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip/req/req_set.py", line 742, in install
    **kwargs
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 831, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 1032, in move_wheel_files
    isolated=self.isolated,
  File "/Library/Python/2.7/site-packages/pip/wheel.py", line 378, in move_wheel_files
    clobber(source, dest, False, fixer=fixer, filter=filter)
  File "/Library/Python/2.7/site-packages/pip/wheel.py", line 317, in clobber
    ensure_dir(destdir)
  File "/Library/Python/2.7/site-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 1] Operation not permitted: '/System/Library/Frameworks/Python.framework/Versions/2.7/share'
```

**Comment by avirshup** [comment]
Manually uploaded conda packages, which should hopefully get around this whole mess
